global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ugo-ai-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Ugo AI API service
  - job_name: 'ugo-api'
    static_configs:
      - targets: ['ugo-api:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: false
    params:
      format: ['prometheus']

  # Model service monitoring
  - job_name: 'model-service'
    static_configs:
      - targets: ['model-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 45s
    scrape_timeout: 15s

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx reverse proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node.js application metrics (if prom-client is used)
  - job_name: 'node-app-metrics'
    static_configs:
      - targets: ['ugo-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics (if node_exporter is added)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        # - 'node-exporter:9100'
    scrape_interval: 30s
    scrape_timeout: 10s
