name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        python-version: ["3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install backend deps
        working-directory: backend
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Lint backend
        working-directory: backend
        run: |
          if [ -f package.json ]; then npm run lint || echo "Lint warnings"; fi

      - name: Test backend
        working-directory: backend
        env:
          NODE_ENV: test
        run: |
          if [ -f package.json ]; then npm test || echo "Tests failed (continuing)"; fi

      - name: npm audit (high)
        working-directory: backend
        run: |
          if [ -f package.json ]; then npm audit --audit-level=high || true; fi

      - name: Build backend Docker (smoke)
        working-directory: backend
        run: |
          docker build -t ugo-backend:test .

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No Python deps"; fi

      - name: Python security audit (pip-audit or safety)
        run: |
          pip install --upgrade pip >/dev/null 2>&1 || true
          pip install pip-audit safety >/dev/null 2>&1 || true
          if [ -f requirements.txt ]; then pip-audit || safety check || true; else echo "No Python requirements"; fi

      - name: Pytest (if present)
        run: |
          if [ -f tests ] || [ -f pytest.ini ] || [ -f pyproject.toml ]; then pytest || echo "Pytests failed (continuing)"; else echo "No Python tests"; fi
